# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ade2a9afaa9200a5344a55a311738e39966aac96485eea96659617efd262596878bd54e62f1c79c537c99f9ab0784e2e40a6332d0bc2d7b6ee4caa191bcf382d

test:
  secret_key_base: 1f2929ea118e612dd41e09b98c06d0713013c4e92c30dfbaf63c5905d25fa91b9e0038fc7b0b19ab339b02bcc100b0d9eb628d2a66573bf10fc1e5ff67914dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
